/* Lista-02 - Figura P7.15.Fisico: */

CREATE TABLE COSTUMER (
    CUS_CODE INT PRIMARY KEY,
    CUS_LNAME CHAR(20),
    CUS_FNAME CHAR(20),
    CUS_INITIAL CHAR(2),
    CUS_AREACODE INT,
    CUS_PHONE CHAR(8),
    CUS_BALANCE DECIMAL(8,2)
);

CREATE TABLE INVOICE (
    INV_NUMBER INT PRIMARY KEY,
    INV_DATE DATE,
    CUS_CODE INT,
    FOREIGN KEY(CUS_CODE) REFERENCES COSTUMER(CUS_CODE)
);

CREATE TABLE LINE (
    LINE_NUMBER INT,
    LINE_UNITS INT,
    LINE_PRICE DECIMAL(8,2),
    INV_NUMBER INT,
    P_CODE CHAR(8),
    PRIMARY KEY(LINE_NUMBER, INV_NUMBER),
    FOREIGN KEY(INV_NUMBER) REFERENCES INVOICE(INV_NUMBER),
    FOREIGN KEY(P_CODE) REFERENCES PRODUCT(P_CODE)
);

CREATE TABLE PRODUCT (
    P_CODE CHAR(8) PRIMARY KEY,
    P_DESCRIPT CHAR(80),
    P_INDATE DATE,
    P_QOH INT,
    P_MIN INT,
    P_PRICE DECIMAL(8,2),
    P_DISCOUNT DECIMAL(2,2),
    V_CODE INT,
    FOREIGN KEY(V_CODE) REFERENCES VENDOR(V_CODE)
);

CREATE TABLE VENDOR (
    V_CODE INT PRIMARY KEY,
    V_NAME CHAR(30),
    V_CONTACT CHAR(10),
    V_AREACODE INT,
    V_PHONE CHAR(8),
    V_ORDER CHAR(1),
    V_STATE CHAR(2),
);
